language: java

jdk:
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk-ea

# Java 13 support is planned for Gradle 6.0
matrix:
  allow_failures:
    - jdk:
        - openjdk13
        - openjdk14
        - openjdk-ea

addons:
  apt:
    packages:
      - lintian

deploy:
  provider: releases
  api_key: "${API_KEY}"
  file:
    - "build/libs/LunaticSMTP-${TRAVIS_TAG}.jar"
    - "build/distributions/lunaticsmtp_${TRAVIS_TAG:1}-1_all.deb"
  skip_cleanup: true
  on:
    tags: true

script:
  - gradle releaseDeb -Dtest.profile=headless
  - lintian build/distributions/*.deb -v --pedantic --suppress-tags debian-changelog-file-missing,manpage-not-compressed
